version: "3"
services:
  mysql:
    image: mysql:8.0.34
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-log-bin

  grafana:
    image: devlake.docker.scarf.sh/apache/devlake-dashboard:latest
    build:
      context: grafana/
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    restart: always
    depends_on:
      - mysql

  devlake:
    image: devlake.docker.scarf.sh/apache/devlake:latest
    build:
      context: backend
      args:
        HTTPS_PROXY: "${HTTPS_PROXY}"
        GOPROXY: "${GOPROXY}"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - devlake-log:/app/logs
    env_file:
      - ./.env
    environment:
      LOGGING_DIR: /app/logs
      TZ: UTC
    depends_on:
      - mysql

  config-ui:
    image: devlake.docker.scarf.sh/apache/devlake-config-ui:latest
    build:
      context: "config-ui"
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      TZ: UTC
      #ADMIN_USER: devlake
      #ADMIN_PASS: letsdivein
    depends_on:
      - devlake

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
